apiVersion: v1
kind: Secret
metadata:
    name: admin-area-secret
type: Opaque
data:
    password: ENC[AES256_GCM,data:7wDg6pqZ6wxddnHJ,iv:Xdy2tVDLdV/fNMvIvjlcfD5Xbv4vm8qqMFyYj6VatYg=,tag:cFy2ndV9rDxMYKhNm1CWTg==,type:str]
    user: ENC[AES256_GCM,data:iw4ktY6f9j0=,iv:zrGfA697xxqsV4WggIIxtZOhN1aT01dXmOSdCP/smws=,tag:lehqWzexbCurpQpcO7Su4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eevg9aaev4l0eh378ckl6lsgxnqvu5s2cwxqdram89jp3ujhs52s2vkw0u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMemlLeElVb0JCK2JMQmVq
            dFd2QVJOQmlrbXZDRm91QlYzR2xTWnlROFdRCkIwVFZ4T0JvSDlEcDBJeGU0N0Fm
            UWQ1bzJYdGdKM0RxR1hxbko1NnJvWGsKLS0tIEFlbG0rN01HTG9hL3NOajhzc3JP
            dDJqdUdsL2NCQlAza2NUdXlxZ0VqRHMKugxlgKB3xvwu9XRnkMy7V1EF1T4Ag9ip
            8Ug74P3WPMca0UqEKV9/HlzNWMz/g3COaG2GMHBtCTuFEx1inBhXmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-06T13:38:12Z"
    mac: ENC[AES256_GCM,data:T7svJ2jngthGNeriN6uKbB1qRlPkI/Bi4TqOIjJWFtswBBUhZOjA5yuWy/oOtRvg9nxUvB8XOCGW+WARfCMCUbLpYK3AQpauIOxa+JH7wON5q2KFl851vGqTuWvmkoTX8TqmsByUBancY/C0PrBoyVj/GF2EWA86JSbedIzuhMA=,iv:esdN+gqaJOnKLParNz+B4tb13uE8mHVVaIb+S8SGjKU=,tag:/r1wWMAVy8AoQfsP2M2bSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
