apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-area-depl
spec:
  selector:
    matchLabels:
      app: admin-area-depl
  template:
    metadata:
      labels:
        app: admin-area-depl
    spec:
      containers:
      - name: admin-area-depl
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: admin-area-config
          - secretRef:
              name: admin-area-secret
