apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: goapp-batch12
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: goapp-batch12
  policy:
    numerical:
      order: asc